---
named_routes:
- name: archive
  route:
  - name: lustre_to_irods
    transformations:
    - name: strip_common_prefix
    - name: prefix
      options:
        prefix: /humgen/{{ scratch_disk }}-backup/{{ project }}/
    - name: telemetry
    - name: debugging
